services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sec
      # useful for connecting from admirer a.k.a. localhost address of mysql:
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - my-network

  adminer:
    image: adminer
    restart: always
    ports:
      # externally exposed to 8081:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  # This is a common pattern in docker-compose files when you want to explicitly create a network for services
  # but don’t need any specific configuration for the network (e.g., driver, external network, etc.).
  my-network: