# root/root as user/password with root privileges:
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sec
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    #container_name: adminer
    ports:
      # externally exposed in 8089:
      - "8081:8080"
    depends_on:
      - mysql