services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sec
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      # useful for connecting with admirer:
      MYSQL_ROOT_HOST: '%'
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      # The docker-entrypoint-initdb.d directory is a special directory used by the MySQL Docker image.
      # When the MySQL container starts for the first time, it will automatically execute any .sql, .sh, or .sql.gz files found in this directory.
      # This is useful for initializing the database with schemas, tables, or users.
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      # externally exposed to 8081:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  # This is a common pattern in docker-compose files when you want to explicitly create a network for services
  # but don’t need any specific configuration for the network (e.g., driver, external network, etc.).
  my-network: