services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sec
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      # useful for connecting with admirer:
      MYSQL_ROOT_HOST: '%'
      # added to skip time zone info initialization, which can sometimes cause issues
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - "3306:3306"
    networks:
      - my-network
    command: --default-authentication-plugin=caching_sha2_password

  adminer:
    image: adminer
    restart: always
    ports:
      # externally exposed to 8081:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  # This is a common pattern in docker-compose files when you want to explicitly create a network for services
  # but don’t need any specific configuration for the network (e.g., driver, external network, etc.).
  my-network: